# /tcl/hide-tilde-files.tcl

ad_library {
    Keeps backup files from being served
    
    @author Original Author Unknown
    @creation-date Original Date Unknown
    @cvs-id hide-tilde-files.tcl,v 3.1.6.1 2000/07/16 19:38:51 ryanlee Exp
}

ns_log Notice "Registering /*~ to a proc so that backup files won't be served to users."

ad_register_proc GET /*~ ad_hide_tilde_files
ad_register_proc POST /*~ ad_hide_tilde_files
ad_register_proc HEAD /*~ ad_hide_tilde_files

proc ad_hide_tilde_files {ignore} {
    ad_return_error "Reference to backup file" "You asked for a URL that ends in ~.  This would be a backup file generated by the Emacs text editor and is probably not what you want."
    return
}
