# $Id: hide-tilde-files.tcl,v 3.0 2000/02/06 03:13:43 ron Exp $
ns_log Notice "Registering /*~ to a proc so that backup files won't be served to users."

ns_register_proc GET /*~ ad_hide_tilde_files
ns_register_proc POST /*~ ad_hide_tilde_files
ns_register_proc HEAD /*~ ad_hide_tilde_files

proc ad_hide_tilde_files {ignore} {
    ad_return_error "Reference to backup file" "You asked for a URL that ends in ~.  This would be a backup file generated by the Emacs text editor and is probably not what you want."
    return
}
