# $Id: element-list.tcl,v 3.0 2000/02/06 03:16:00 ron Exp $
#
# /admin/curriculum/element-list.tcl
#
# the main admin page for the curriculum system
# autogenerated by the prototype tool and then 
# hacked a bit by philg@mit.edu
# 

ReturnHeaders

ns_write "[ad_admin_header "Curriculum" ]
<h2>Curriculum</h2>


[ad_admin_context_bar "Curriculum"]

<hr>

Documentation:  <a href=\"/doc/curriculum.html\">/doc/curriculum.html</a>

<h3>How the users are doing</h3>

<blockquote>
<table cellspacing=5>
<tr>
  <th valign=top>Curriculum Elements<br>Completed
  <th valign=top>Number of Users
</tr>
"

set db [ns_db gethandle]
set selection [ns_db select $db "select nvl(n_rows,0) as n_rows, count(*) as n_users
from users, (select user_id, count(*) as n_rows
             from user_curriculum_map, curriculum
             where user_curriculum_map.curriculum_element_id = curriculum.curriculum_element_id
             group by user_id) user_row_stats
where users.user_id = user_row_stats.user_id(+)
group by nvl(n_rows,0)
order by nvl(n_rows,0) desc"]

set table_rows ""
while { [ns_db getrow $db $selection] } {
    set_variables_after_query
    append table_rows "<tr>
  <td align=right>$n_rows
  <td align=right><a href=\"/admin/users/action-choose.tcl?curriculum_elements_completed=$n_rows\">$n_users</a></tr>\n"
}

ns_write "$table_rows

</table>
</blockquote>
<h3>All the curriculum elements</h3>
<ul>"


set sql_query  "select element_index, very_very_short_name, one_line_description, curriculum_element_id
from curriculum
order by element_index"
set selection [ns_db select $db $sql_query] 

set counter 0
while { [ns_db getrow $db $selection] } {
    set_variables_after_query
    incr counter
    ns_write "<li>$element_index: <a href=\"element-view.tcl?[export_url_vars curriculum_element_id]\">$very_very_short_name</a> ($one_line_description)<br>\n"
}

if { $counter == 0 } {
    ns_write "<li>There are no curriculum elements in the database right now.<p>"
}

ns_write "<p><li><a href=\"element-add.tcl\">Add a curriculum element</a></ul><p>
[ad_admin_footer]"
