---
# Copy over export script and add to root's crontab.
# Created: Tue Sep 17 16:56:17 EDT 2013

- name: Copy over export script.
  template: src=acs_export-oracle.sh.j2
      dest=/usr/sbin/export-oracle
      owner=root group=wheel 
      mode=0700

- name: Add script to root's crontab.
  cron: name="Nightly Oracle export" hour=23 minute=0 job=/usr/sbin/export-oracle
