---
# Run SQL to allow the ACS to run the Oracle monitoring reports.

- name: Copy over SQL to create the ad_cassandracle role.
  template: src=acs_enable_cassandra.sql.j2
      dest={{ ORACLE_OWNER_HOME }}/enable_cassandracle.sql 
      owner={{ ORACLE_OWNER }}  group={{ ORACLE_OWNER }} 

- name: Run SQL to create the ad_cassandracle role.
  command: su - {{ ORACLE_OWNER }}  -c "sqlplus /nolog @enable_cassandracle.sql" 
