---
# Copy over and extract the ACS sources.
# Created: Mon Sep  2 15:30:28 EDT 2013

- name: Copy the ACS source tarball to the destination host.
  copy: src=acs-{{ ACS_VERSION }}.tgz dest=/tmp
          owner={{ AOL_SERVER_USER }} group={{ AOL_SERVER_USER }} mode=644

- name: Make sure /web/acs directory does not already exist.
  file: path={{ AOL_SERVER_WEBROOT }}/acs state=absent

- name: Extract the ACS sources.
  command: tar -zxf /tmp/acs-{{ ACS_VERSION }}.tgz -C {{ AOL_SERVER_WEBROOT }}

- name: Rename ACS sources to use our domain name.
  command: mv {{ AOL_SERVER_WEBROOT }}/acs {{ AOL_SERVER_WEBROOT }}/{{ ACS_DOMAIN_NAME }}

# XXX: figure out what mode to give to files and directories
- name: Change permissions on extracted file to AOL server user.
  file: path={{ AOL_SERVER_WEBROOT }}/{{ ACS_DOMAIN_NAME }} state=directory 
          owner={{ AOL_SERVER_USER }} group={{ WEB_GROUP }} 
          recurse=yes
