---
# Load the ACS initial geographicsl data
# Created: Mon Sep  2 18:17:03 EDT 2013

- name: Make load-geo-tables executable.
  file: path={{ AOL_SERVER_WEBROOT }}/{{ ACS_DOMAIN_NAME }}/www/install/load-geo-tables mode=755

- name: Load the data.
  shell: su - nsadmin -c "cd {{ AOL_SERVER_WEBROOT }}/{{ ACS_DOMAIN_NAME }}/www/install && ./load-geo-tables {{ ACS_ORACLE_USER }}/{{ ACS_ORACLE_PASSWORD }} > /tmp/load-geo-tables.log" 

