---
# Configure ACS service.
# Created: Thu Sep  5 18:04:53 EDT 2013

- name: Create $DOMAIN_NAME.tcl for the ACS.
  template: src=acs_acs.tcl.j2 dest={{ AOL_HOME }}/{{ ACS_DOMAIN_NAME }}.tcl
      owner={{ AOL_SERVER_USER }} group={{ AOL_SERVER_USER }}
      mode=644

# XXX: Not sure about directory modes for these next few.
- name: Create directory for the ACS logs.
  file: path={{ AOL_HOME }}/log state=directory
      owner={{ AOL_SERVER_USER }} group={{ WEB_GROUP }} mode=755

- name: Create directory for the ACS web app.
  file: path={{ AOL_SERVER_WEBROOT }}/{{ ACS_DOMAIN_NAME }} state=directory
      owner={{ AOL_SERVER_USER }} group={{ WEB_GROUP }} mode=755

- name: Create directory for the ACS web files.
  file: path={{ AOL_SERVER_WEBROOT }}/{{ ACS_DOMAIN_NAME }}/web state=directory
      owner={{ AOL_SERVER_USER }} group={{ WEB_GROUP }} mode=755

- name: Create directory for the ACS web app parameters.
  file: path={{ AOL_SERVER_WEBROOT }}/{{ ACS_DOMAIN_NAME }}/parameters state=directory
      owner={{ AOL_SERVER_USER }} group={{ WEB_GROUP }} mode=755

- name: Copy over site parameters
  template: src=acs_ad.tcl.j2 
      dest={{ AOL_SERVER_WEBROOT }}/{{ ACS_DOMAIN_NAME }}/parameters/{{ ACS_DOMAIN_NAME }}.tcl
      owner={{ AOL_SERVER_USER }} group={{ AOL_SERVER_USER }}
      mode=644

- name: Create symlink to perl in /usr/local/bin so ACS scripts work.
  file: src=/usr/bin/perl dest=/usr/local/bin/perl owner=root group=root state=link
