---
# Install AOL server.
# ref: http://www.eveandersson.com/arsdigita/acs-install/aolserver

# XXX: Figure out how to build tarball if needed.
# Output from the following was:
#     failed: [192.168.67.10] => {"failed": true, "item": "", "parsed": false}
#     invalid output was: [sudo via ansible, key=jyinfugcmdnbbiirxftevlslhnjgvkbz] password:
#     Sorry, try again.
#- name: Check if we need to fetch tarball.
#  command: test -f aolserver-3.3.0.tgz
#  delegate_to: 127.0.0.1
#  register: need_tarball
#  ignore_errors: True

- name: Add nsadmin group
  group: name=nsadmin state=present

- name: Add web group
  group: name=web state=present

- name: Create the nsadmin user, which runs AOL Server.
  user: name=nsadmin group=nsadmin groups=dba,web home={{ AOL_HOME }}

- name: Copy over .bashrc for nsadmin user.
  template: src=bashrc.j2 dest={{ AOL_HOME }}/.bashrc
      owner=nsadmin group=nsadmin

- name: Set user.group on nsadmin home to nsadmin.web.
  file: path={{ AOL_HOME }} state=directory recurse=yes
          owner=nsadmin group=web mode=755

- name: Create /web directory, where web server files will live.
  file: path=/web owner=nsadmin group=web mode=755 state=directory

- name: Create directory where compiles AOL Server files will live.
  file: path=/usr/local/aolserver state=directory
          owner=nsadmin group=web mode=755

#---------------------------------------------------------------------------
#
#                             A O L   S E R V E R
#
#---------------------------------------------------------------------------
- name: Copy over AOL Server source code.
  copy: src=aolserver-{{ AOL_TAG }}.tgz dest=/tmp
          owner=nsadmin group=nsadmin mode=644

- name: Delete old AOL extrated sources.
  file: path=/tmp/aolserver state=absent

- name: Extract AOL Server sources.
  command: tar -zxf /tmp/aolserver-{{ AOL_TAG }}.tgz -C /tmp

- name: Copy over TCL source.
  copy: src={{ AOL_TCL_TARBALL }}
          dest=/tmp owner=nsadmin group=nsadmin mode=644

- name: Extract TCL source.
  command: tar -zxf /tmp/{{ AOL_TCL_TARBALL }} -C /tmp/aolserver --overwrite

- name: Copy over new TCL header file to AOL Server include directory.
  command: cp
          /tmp/aolserver/{{ AOL_TCL }}/generic/tcl.h
          /tmp/aolserver/include/tcl84.h

- name: Copy over 8.4 TCL declarations header file to AOL Server include directory.
  command: cp
          /tmp/aolserver/{{ AOL_TCL }}/generic/tclDecls.h
          /tmp/aolserver/include

- name: Copy over 8.4 TCL declarations header file to AOL Server include directory.
  command: cp
          /tmp/aolserver/{{ AOL_TCL }}/generic/tclPlatDecls.h
          /tmp/aolserver/include

#tclIntDecls.h
#tclIntPlatDecls.h
#tclPlatDecls.h

- name: Copy over AOL patch so build uses TCL 8.4.20.
  copy: src=aol_tcl8.4.20.patch
          dest=/tmp/aolserver owner=nsadmin group=nsadmin mode=644

- name: Apply AOL/TCL patch.
  shell: /usr/bin/patch -p0 < aol_tcl8.4.20.patch chdir=/tmp/aolserver

- name: Compile and install AOL Server.
  shell: make install chdir=/tmp/aolserver

- name: Change user.group back to nsadmin.web
  file: path=/usr/local/aolserver state=directory
          owner=nsadmin group=web mode=755

# To access from host machine.
#
#   1. Copy /usr/bin/aolserver/sample-config.tcl to config.tcl
#   2. Apply this patch:
#
#     --- sample-config.tcl2013-08-31 12:10:35.000000000 -  0700
#     +++ config.tcl
#     --- sample-config.tcl2013-08-31 12:10:35.000000000 -0700
#     +++ config.tcl2013-09-0   1 09:00:42.000000000 -0700
#     @@ -20,7 +20,8 @@
#    
#      # The hostname and address should be set to actual values.
#       set hostname               [ns_info hostname]
#       -set address                [ns_info address]
#       +#set address                [ns_info address]
#       +set address                192.168.67.10
#    
#        set servername             "server1"
#        set serverdesc             "Server Name"
#

#---------------------------------------------------------------------------
#
#               A O L   S E R V E R    O R A C L E   D R I V E R
#
#---------------------------------------------------------------------------
- name: Copy over AOL Server Oracle driver source code.
  copy: src=nsoracle-{{ AOL_ORACLEDRIVER_TAG }}.tgz dest=/tmp
          owner=nsadmin group=nsadmin mode=644

- name: Delete old AOL extrated sources.
  file: path=/tmp/nsoracle state=absent

- name: Extract AOL Oracle driver sources.
  command: tar -zxf /tmp/nsoracle-{{ AOL_ORACLEDRIVER_TAG }}.tgz -C /tmp

- name: Copy over nsoracle patch so build.
  copy: src=aol_nsoracle.patch dest=/tmp/nsoracle

- name: Apply nsoracle patch.
  shell: /usr/bin/patch -p0 < aol_nsoracle.patch chdir=/tmp/nsoracle

- name: Compile and install Oracle driver for AOL Server.
  shell: ORACLE_HOME={{ ORACLE_HOME }} make install chdir=/tmp/nsoracle
