- hosts: vagrant
  sudo: yes
  vars:
    ORACLE_BASE: /home/oracle/app/oracle
    ORACLE_HOME: $ORACLE_BASE/product/11.2.0/dbhome_2
  tasks:

  # XXX: Dry up the ORACLE_* values (use template + variable substitution).
  - name: Set up .bashrc for oracle user.
    copy: src=oracle.bashrc dest=/home/oracle/.bashrc owner=oracle group=oracle

  - name: Copy over initialization paramters for ora11
    copy: src=initora11.ora dest={{ORACLE_HOME}}/dbs owner=oracle group=oracle
