# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "oracle_11.2g"

  config.vm.network :private_network, ip: "192.168.67.10"

  # Uncomment to debug.
  #config.vm.provider "virtualbox" do |v|
  #  v.gui = true
  #end

end
