---
# Configure Oracle Express to use a date format of YYYY-MM-DD (which the ACS
# requires).
# Created: Sat Oct  5 15:38:45 EDT 2013
#
# The ACS documentation say to set the NLS_DATE_FORMAT PARAMETER.
# But the NLS_LANG (National Language Support) overrides that setting.  
#
# The NLS_LANG is pretty interesting.  Or, rather, the character encoding
# part of the NLS.  Both a server and the client (or session, to be more
# precise) can have their own NLS setting.  For example, a Windows client
# that does not support UTF8 encoding can talk with a database on Linux that
# is storing characters in UTF8.  For this to work, the session must be using
# the character encoding of the Windows client; perhaps WE8MSWIN1252. 
#
# In addition, there is are NLS settings for the database, instance and
# session.
#
#   database - set from the instance when "CREATE DATABASE" executed.
#   instance - set by pfile (init.ora) or spfile
#   session  - for the current client session (env vars or alter system)
#
# The priority goes: session > instance > database.
#
# You can view the current settings by:
#
#     select * from NLS_DATABASE_PARAMETERS;
#     select * from NLS_INSTANCE_PARAMETERS;
#     select * from NLS_SESSION_PARAMETERS;
#
# Here are the values for the default Oracle Express Install:
#
#      SELECT * FROM NLS_DATABASE_PARAMETERS
#      ;
#      PARAMETER                VALUE
#      -----------------------  -------------------------
#      NLS_LANGUAGE             AMERICAN
#      NLS_TERRITORY            AMERICA
#      NLS_CURRENCY             $
#      NLS_ISO_CURRENCY         AMERICA
#      NLS_NUMERIC_CHARACTERS   .,
#      NLS_CHARACTERSET         AL32UTF8
#      NLS_CALENDAR             GREGORIAN
#      NLS_DATE_FORMAT          DD-MON-RR
#      NLS_DATE_LANGUAGE        AMERICAN
#      NLS_SORT                 BINARY
#      NLS_TIME_FORMAT          HH.MI.SSXFF AM
#      NLS_TIMESTAMP_FORMAT     DD-MON-RR HH.MI.SSXFF AM
#      NLS_TIME_TZ_FORMAT       HH.MI.SSXFF AM TZR
#      NLS_TIMESTAMP_TZ_FORMAT  DD-MON-RR HH.MI.SSXFF AM TZR
#      NLS_DUAL_CURRENCY        $
#      NLS_COMP                 BINARY
#      NLS_LENGTH_SEMANTICS     BYTE

#      NLS_NCHAR_CHARACTERSET   AL16UTF16
#      NLS_RDBMS_VERSION        11.2.0.2.0
#
#      SELECT * FROM NLS_INSTANCE_PARAMETERS
#      ;
#      PARAMETER                VALUE
#      -----------------------  -------------------------
#      NLS_LANGUAGE             AMERICAN
#      NLS_TERRITORY            AMERICA
#      NLS_SORT
#      NLS_DATE_LANGUAGE
#      NLS_DATE_FORMAT
#      NLS_CURRENCY
#      NLS_NUMERIC_CHARACTERS
#      NLS_ISO_CURRENCY
#      NLS_CALENDAR
#      NLS_TIME_FORMAT
#      NLS_TIMESTAMP_FORMAT
#      NLS_TIME_TZ_FORMAT
#      NLS_TIMESTAMP_TZ_FORMAT
#      NLS_DUAL_CURRENCY
#      NLS_COMP                 BINARY
#      NLS_LENGTH_SEMANTICS     BYTE
#      NLS_NCHAR_CONV_EXCP      FALSE
#
# And, in SQL Developer, the SESSION parameters come right from the datbase.:
#
#       select count(*) from NLS_SESSION_PARAMETERS;
#       > 17
#
#       select    count(*) 
#       from      (
#                   select    s.*
#                             , d.value 
#                   from      NLS_SESSION_PARAMETERS s
#                             join nls_database_parameters d 
#                               on s.parameter = d.parameter 
#                               and s.value = d.value
#                  );
#       > 17
#
# To set the NLS_DATE_FORMAT to the required "YYYY-MM-DD" format, we need to
# change the instance-level setting.  Since XE is using the spfile (see SQL in
# /u01/app/oracle/product/11.2.0/xe/config/scripts/postDBCreation.sql), we
# need to:
#
#       Add NLS_DATE_FORMAT to /u01/app/oracle/product/11.2.0/xe/config/scripts/init.ora.
#
#       sqlplus oracle/oracle as sysdba
#       > shutdown
#       > create spfile from pfile='$ORACLE_HOME/config/scripts/init.ora';
#       > startup
#       
# Finally, note that SQL-Developer has it's own client settings! Since session
# settings override instance settings, if you are using SQL Developer, you
# won't see the impact of change to init.ora.  You need to check in SQLPlus.
#

- name: Add NLS_DATE_FORMAT line to init.ora.
  lineinfile: dest={{ ORACLE_HOME }}/config/scripts/init.ora 
     regexp="^NLS_DATE_FORMAT.*" 
     line="NLS_DATE_FORMAT=\"YYYY-MM-DD\""
  register: initora1

- name: Increase open_cursors from 300 to 500.
  lineinfile: dest={{ ORACLE_HOME }}/config/scripts/init.ora 
     regexp="^open_cursors="
     line="open_cursors=500"
  register: initora2

- name: Copy over SQL to setup Oracle instance settings.
  template: src=xe_reload_initora.sql.j2 dest={{ ORACLE_USER_HOME }}/reload_initora.sql 
    owner={{ ORACLE_USER }} group={{ ORACLE_GROUP }} 
  when: initora1.changed or initora2.changed

- name: Run SQL to reconfigure Oracle instance settings.
  command: su - {{ ORACLE_USER }} -c "sqlplus /nolog @reload_initora"
  when: initora1.changed or initora2.changed
